### ISSUE TITLE
Screenshots copied to clipboard stored as plain text

### ISSUE THREAD

**Issue by pagusupu** [Gustash/Hyprshot#28] opened 2024-01-15 00:44 UTC
Running `hyprshot -m region` saves the image properly but copies to clipboard:
![2024-01-15-134136_hyprshot](https://github.com/Gustash/Hyprshot/assets/114620038/7347f236-48df-45d6-b70b-4e9c64464b6a)

**Comment by ProMix0** [comment] 2024-01-27 22:53
Can't reproduce. Could you say what version of hyprshot you use and how do you start it?

**Comment by Gustash** [comment] 2024-06-01 18:43
Fixed in #35

**Closed by Gustash** 2024-06-01 18:43 UTC
